title: QArmyJapanFlynn  # サイトのタイトル
description: >- # サイトの説明を書く
  サイトの説明を書いてください。
  200文字程度がいいと一般には言われていたりします。

baseurl: "" # ここは無視してOKです
url: "https://qajf.github.io" # サイトのドメインを入力します。
google_analytics: UA-221673806-1

plugins: # 使用するプラグインがあればここに追加します
  - jekyll-feed
markdown: kramdown

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
exclude: # サイトの生成に含めないものをここに追加します
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
